import React from "react";

const Collection = () => {
  return (
    <div className="flex flex-col">
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
      <span>LIB</span>
    </div>
  );
};

export default Collection;
